trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  global_variable: value    # this is available to all jobs
  
stages:
- stage: buildMGM
  displayName: buildMGM
  jobs:
  - job: job1
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_variable1: value1    # this is only available in job1
    steps:
    - bash: echo $(global_variable)
    - bash: echo $(job_variable1)
    - bash: echo $JOB_VARIABLE1 # variables are available in the script environment too

- stage: UnitTestMGM
  displayName: UnitTestMGM
  jobs:
  - job: job1
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_variable1: value1    # this is only available in job1
    steps:
    - bash: echo $(global_variable)
    - bash: echo $(job_variable1)
    - bash: echo $JOB_VARIABLE1 # variables are available in the script environment too
 
 