trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: "pipelineName"
  value: IntercorpCommon
  
stages:
- stage: Build
  displayName: 'Build : Intercorp'
  jobs:
  - job: 'StageBuild_jobBegin'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** [Stage: Build | Job: Begin - INTERCORP]   ****'
    steps:
    - bash: echo $(job_message)