trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: "pipelineName"
  value: IntercorpCommon
  
stages:
- stage: Build
  displayName: 'Build : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [BUILD - INTERCORP]   ****'
    steps:
    - bash: echo $(job_message)

- stage: UnitTest
  displayName: 'Unit Test : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [UNIT TEST - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
    
- stage: CodeAnalysis
  displayName: 'Unit Test : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [CODE ANALYSIS - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
 
- stage: Package
  displayName: 'Package : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [PACKAGE - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)

- stage: AutomatedTest
  displayName: 'Automated Test : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [AUTOMATED TEST - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
    
- stage: Integration
  displayName: 'Integration : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [INTEGRATION TEST - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
 
- stage: Release
  displayName: 'Release : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [Release - INTERCORP] ****'
    steps:
    - bash: echo $(job_message) 
 
- stage: DeployInfrastructure
  displayName: 'Deploy Infrastructure : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [Deploy Infrastructure - INTERCORP] ****'
    steps:
    - bash: echo $(job_message) 
 
- stage: DeployApplication
  displayName: 'Deploy Application : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [Deploy Application - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
    
- stage: DeployConfiguration
  displayName: 'Deploy Configuration : Intercorp'
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE [Deploy Configuration - INTERCORP] ****'
    steps:
    - bash: echo $(job_message)
