trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  
stages:
- stage: Build
  displayName: Build : IR-Digital
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE BUILD - INTERCORP ****'
    steps:
    - bash: echo $(job_message)

- stage: UnitTest
  displayName: Unit Test : IR-Digital
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE UNIT TEST - INTERCORP ****'
    steps:
    - bash: echo $(job_message)
    
- stage: CodeAnalysis
  displayName: Unit Test : IR-Digital
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE CODE ANALYSIS - INTERCORP ****'
    steps:
    - bash: echo $(job_message)
 
- stage: Package
  displayName: Package : IR-Digital
  jobs:
  - job: StageBegin
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_message: '**** STAGE PACKAGE - INTERCORP ****'
    steps:
    - bash: echo $(job_message)